server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity_service
    username: root
    password: vuong2003
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

jwt:
  signerKey: "RGTpEo990czwgYq+8gfA5Z56nVJcjQi25cPKtaJ+hapof7rMtBoZkat9pkqdvWpv"
  valid-duration: 3600 # in seconds
  refreshable-duration: 360000 # in seconds